
application:
  port: 8000
  hmac_secret: "super-long-secret-that-you-dont-tell-anyone-used-for-message-integrity"
database:
  host: "localhost"
  port: 5432
  username: "postgres"
  password: "password"
  database_name: "newsletter"
email_client:
  sender_email: "dionethedeveloper@gmail.com"
  base_url: "localhost"
  authorization_token: "my-secret-token"
  timeout_milliseconds: 10000
