
application:
  port: 8000
  hmac_secret: "super-long-secret-that-you-dont-tell-anyone-used-for-message-integrity"
database:
  host: "localhost"
  port: 5432
  username: "postgres"
  password: "password"
  database_name: "newsletter"
email_client:
  base_url: "https://api.postmarkapp.com"
  sender_email: "dione.morales@students.mq.edu.au"
  authorization_token: "POSTMARK_API_TEST"
  timeout_milliseconds: 10000
redis_uri: "redis://127.0.0.1:6379"